about/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.about_project, name="about"),
    path("contact_us/", views.send_message, name="send_message"),
]

be_a_dear/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('about/', include("about.urls"), name="about"),
    path("accounts/", include("allauth.urls")),
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include("volunteer.urls"), name="volunteer-urls"),
]

volunteer/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.home, name="home"),
    path('student_dashboard/', views.student_dashboard,
         name="student_dashboard"),
    path('student_dashboard/delete_task/<int:slot_id>/',
         views.delete_via_dashboard, name='delete_via_dashboard'),
    path('<slug:slug>/', views.beneficiary_detail,
         name="beneficiary_detail"),
    path('<slug:slug>/edit_slot/<int:slot_id>/',
         views.slot_edit, name="slot_edit"),
    path('<slug:slug>/delete_slot/<int:slot_id>/',
         views.slot_delete, name="slot_delete"),
    path('update_task/<int:pk>/',
         views.update_slot, name="update_slot"),
    path('volunteer/volunteer_opportunities/', views.BeneficiaryList.as_view(),
         name="beneficiaries"),
]

volunteer/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField

STATUS = (
    (0, "Draft"),
    (1, "Published")
    )

CLASS_YEARS = (
    ("FR", "Freshman"),
    ("SO", "Sophmore"),
    ("JR", "Junior"),
    ("SR", "Senior"),
    ("UA", "Unassigned"),
    )

COMPLETION = (
    (0, "Incomplete"),
    (1, "Completed"),
)


# Create your models here.

class Beneficiary(models.Model):
    """
    Stores a single beneficiary.
    """
    beneficiary_name = models.CharField(max_length=150, unique=True)
    slug = models.SlugField(max_length=150)
    short_description = models.CharField(max_length=255, default="")
    description = models.TextField()
    location = models.CharField(max_length=255, default="")
    contact_details = models.CharField(max_length=200)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    status = models.IntegerField(choices=STATUS, default=0)
    featured_image = CloudinaryField('image', default='placeholder')

    class Meta:
        ordering = ["beneficiary_name"]


class Slot(models.Model):
    """
    Stores a single slot related to :model: Beneficiary
    and :model: auth.User
    """
    beneficiary = models.ForeignKey(Beneficiary,
                                    on_delete=models.CASCADE,
                                    related_name="slots")
    task = models.CharField(max_length=200, default="")
    task_location = models.CharField(max_length=200,
                                     default="(use pseudonym "
                                     "for private beneficiary)")
    dates = models.CharField(max_length=200, default="to be determined")
    times = models.CharField(max_length=200, default="to be determined")
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    reserved_by = models.ForeignKey(User, blank=True,
                                    on_delete=models.CASCADE,
                                    related_name="reservations")
    completed = models.SmallIntegerField(choices=COMPLETION, default=0)
    credit_minutes_requested = models.SmallIntegerField(default=0)
    credit_minutes_approved = models.SmallIntegerField(default=0)
    publish_ok = models.BooleanField(default=False)

    class Meta:
        ordering = ["created_on"]


class Classroom(models.Model):
    """
    Stores a single classroom entry.
    """
    classroom_number = models.CharField(max_length=10, primary_key=True)
    class_year = models.CharField(max_length=10, choices=CLASS_YEARS)

    class Meta:
        app_label = "volunteer"
        ordering = ["classroom_number", "class_year"]

volunteer/forms.py
from django import forms
from .models import Slot


class SlotForm(forms.ModelForm):
    class Meta:
        model = Slot
        fields = [
                    'task',
                    'task_location',
                    'dates',
                    'times',
                    'completed',
                    'credit_minutes_requested',
                ]

volunteer/views.py
from django.shortcuts import render, get_object_or_404, reverse
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import HttpResponseRedirect
from .models import Beneficiary, Slot
from .forms import SlotForm


def home(request):
    return render(request, 'volunteer/index.html', {})


class BeneficiaryList(generic.ListView):
    """
    Generates a list of beneficiaries
    on the volunteer page.
    **Template**
    `volunteer/volunteer_opportunties.html`
    """
    queryset = Beneficiary.objects.filter(
                status=1).order_by("beneficiary_name")
    template_name = "volunteer/volunteer_opportunities.html"


# Adapted from Code Institute lesson, I Think Therefore I Blog
def beneficiary_detail(request, slug):
    """
    Displays an individual of :model: `volunteer.Beneficiary`.
    **Context**
    ``beneficiary``
        An instance of :model: `volunteer.Beneficiary`
    ``slots``
        Shows all slots with public_ok=True related
        to the beneficiary.
    ``form``
        An instance of :form: `volunteer.SlotForm`.
    **Template**
        :template:`volunteer/beneficiary_detail.html`
    """

    queryset = Beneficiary.objects.filter(status=1)
    beneficiary = get_object_or_404(queryset, slug=slug)
    slots = beneficiary.slots.all().order_by("-created_on")
    slots_created_count = beneficiary.slots.all().count()
    slots_completed_count = beneficiary.slots.filter(completed=True).count()
    if request.method == "POST":
        form = SlotForm(request.POST)
        if form.is_valid():
            slot = form.save(commit=False)
            slot.reserved_by = request.user
            slot.beneficiary = beneficiary
            form.save()
            messages.add_message(
                request, messages.SUCCESS,
                "Your slot has been saved and will now appear"
                " on your personal page."
                " It will not be shown publicly on this page"
                " unless and until it is approved for publication."
                )
        else:
            messages.add_message(
                request, messages.ERROR,
                "There has been an error. Please try again! "
                "Contact us through the form on the About page "
                "if the problem persists."
            )

    form = SlotForm()

    return render(
        request,
        "volunteer/beneficiary_detail.html",
        {
            "beneficiary": beneficiary,
            "slots": slots,
            "slots_created_count": slots_created_count,
            "slots_completed_count": slots_completed_count,
            "form": form,
        },
    )


# Adapted from Code Institute lesson, I Think Therefore I Blog
def slot_edit(request, slug, slot_id):
    """
    View to edit a slot directly on the
    beneficiary_detail page.
    **Context**
    `slot`
        An instance of :model: Slot
    ``form``
        An instance of :form: `volunteer.SlotForm`.
    **Template**
        :template:`volunteer/beneficiary_detail.html`
    """
    if request.method == "POST":
        queryset = Beneficiary.objects.filter(status=1)
        beneficiary = get_object_or_404(queryset, slug=slug)
        slot = get_object_or_404(Slot, pk=slot_id)
        slot_form = SlotForm(request.POST, instance=slot)
        if slot_form.is_valid():
            slot = slot_form.save(commit=False)
            slot.beneficiary = beneficiary
            slot.publish_ok = False
            slot.save()
            messages.add_message(request, messages.SUCCESS,
                                 'Your task has been updated!')

        else:
            messages.add_message(request, messages.ERROR,
                                 "An error occurred "
                                 "updating the task")

    return HttpResponseRedirect(
        reverse('beneficiary_detail', args=[slug]))


# Adapted from Code Institute lesson, I Think Therefore I Blog
def slot_delete(request, slug, slot_id):
    """
    View to delete a slot directly on the
    beneficiary_detail page.
    **Context**
    `slot`
        An instance of :model: Slot
    **Template**
        :template:`volunteer/beneficiary_detail.html`
    """
    slot = get_object_or_404(Slot, pk=slot_id)
    if slot.reserved_by == request.user:
        slot.delete()
        messages.add_message(request, messages.SUCCESS,
                             'Your task has been deleted!')
    else:
        messages.add_message(request, messages.ERROR,
                             'You can only delete '
                             'your own tasks.')

    return HttpResponseRedirect(
        reverse('beneficiary_detail', args=[slug]))


def update_slot(request, pk):
    """
    View to update a slot from the student dashboard.
    **Context:**
    `slot`
    An instance of :model: Slot
    `form`
    An instance of :form: volunteer.SlotForm
    ""Template"
    :template: 'volunteer/update_task.html'
    """

    slot = Slot.objects.get(id=pk)
    form = SlotForm(instance=slot)
    user = request.user
    if request.method == "POST":
        form = SlotForm(request.POST, instance=slot)
        if form.is_valid():
            form.save(commit=False)
            slot.publish_ok = False
            slot.save()
            messages.add_message(request, messages.SUCCESS,
                                 'Your task has '
                                 'been updated!')
        else:
            messages.add_message(request, messages.ERROR,
                                 'You can only delete '
                                 'your own tasks.')

        return HttpResponseRedirect(reverse(
                                                'student_dashboard'
                                            ))

    return render(request,
                  'volunteer/update_task.html',
                  {
                    'form': form,
                    'user': user,
                    'slot': slot,
                  },)


@login_required
def student_dashboard(request):
    """
    Renders the student dashboard page.
    **Context**
    ``user``
        an instance of :model: User
    ``slot``
        an instance of :model: Slot
    **Template**
    'student_dashboard.html'
    """
    user = request.user
    slots = Slot.objects.filter(reserved_by=user)

    return render(
        request,
        "volunteer/student_dashboard.html",
        {"slots": slots, }
    )


def delete_via_dashboard(request, slot_id):
    """
    Deletes a selected slot via the
    student dashboard.
    **Context**
    `slot`
    An instance of :model: Slot
    **Template**
    'volunteer/student_dashboard.html'
    """
    slot = get_object_or_404(Slot, pk=slot_id)
    if slot.reserved_by == request.user:
        slot.delete()
        messages.add_message(request, messages.SUCCESS,
                             'Your task has been deleted!')
    else:
        messages.add_message(request, messages.ERROR,
                             'You can only delete your '
                             'own tasks.')

    return HttpResponseRedirect(reverse(
                                        'student_dashboard')
                                )

volunteer/templates/volunteer/beneficiary_detail.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block head_title %}
Beneficiary Details
{% endblock head_title %}

{% block content %}

<!-- Beneficiary detail-->
<section id="beneficiary-information">
    <h1 class="d-none">Beneficiary Information and Saving Tasks</h1>
    <div class="container beneficiary-detail">
        <div class="row d-flex flex-row align-items-center flex-wrap">
            <div class="col-sm-12 col-md-6">
                <div class="card ml-0" style="max-width: 36rem;">
                    {% if "placeholder" in beneficiary.featured_image.url %}
                        <img src="{% static 'images/default-beneficiary.jpg' %}"
                            class="card-img-top" alt="placeholder image">
                    {% else %}
                        <img src="{{ beneficiary.featured_image.url }}"
                            class="card-img-top" 
                            alt="{{ beneficiary.beneficiary_name }}">
                    {% endif %}
                    <div class="card-body">
                        <h5 class="card-title">{{ beneficiary.beneficiary_name }}</h5>
                        <article class="card-text">{{ beneficiary.description | safe }}</article>
                        <p class="card-text">{{ beneficiary.location }}</p>
                        <p class="card-text">{{ beneficiary.contact_details }}</p>
                        <p class="card-text">Tasks planned by WCHS students: 
                            {{ slots_created_count }}</p>
                        <p class="card-text">Tasks completed by WCHS students: 
                            {{ slots_completed_count }}</p>
                    </div>
                </div>
            </div>
            <!-- Reserve slots -->
            <div class="col-sm-12 col-md-6">
                {% if user.is_authenticated %}
                <h3 class="display-4 py-3">Fill in the form to add a task related to 
                    {{ beneficiary.beneficiary_name }} to your dashboard.</h3>
                <h4 class="display-6 py-2">You can manage the details and update your 
                    tasks on your <a href="{% url 'student_dashboard' %}" 
                    aria-label="link to dashboard">dashboard</a>.</h4>
                <p class="graduate-bold pt-2">Reservation for username: 
                    {{ user.username }}</p>
                <form id="slotForm" class="mb-5" method="post">
                    {{ form | crispy }}
                    {% csrf_token %}
                    <button id="submitButton" type="submit" 
                        class="btn btn-secondary btn-lg">Save to Dashboard</button>
                </form>
                {% else %}
                <h3 class="display-2">You must be logged in to save a task 
                    to your dashboard.
                    <a href="{{ login_url }}" 
                        aria-label="link to log in" 
                        class="btn btn-primary btn-lg">Log In</a>
                </h3>
                {% endif %}
            </div>
        </div>
    </div>
</section>
<!--List of published slots (and all reserved by current user) -->
<section id="schoolwide-planned-tasks">
    <h1 class="d-none">Schoolwide Planned Tasks</h1>
    <div class="container-fluid slots-list">
        <div class="row">
            <div class="col-12 p-2 py-5 text-center">
                <h2 class="display-4">What's been saved to students' dashboards:</h2>
                <h3><small>Tasks are listed publicly at the discretion of 
                        school staff (so be polite!)</small>
                </h3>
            </div>
            <div class="row mb-5">
                {% for slot in slots %}
                <div class="col-sm-12 col-md-4 col-lg-3 slot-display
                            {% if not slot.publish_ok and slot.reserved_by == user %}muted
                            {% elif not slot.publish_ok %}d-none
                            {% endif %}">
                    <div class="card">
                        <div class="card-body">
                            <span>Task: </span>
                            <span id="task{{ slot.id }}">{{ slot.task }}</span><br>
                            <span>Location: </span>
                            <span id="task_location{{ slot.id }}">
                                {{ slot.task_location }}</span><br>
                            <span>Dates: </span>
                            <span id="dates{{ slot.id }}">{{ slot.dates }}</span><br>
                            <span>Times: </span>
                            <span id="times{{ slot.id }}">{{ slot.times }}</span><br>
                            <span>Completed: </span>
                            <span id="completed{{ slot.id }}">{{ slot.completed }}</span><br>
                            <span>Credit Minutes Requested: </span>
                            <span id="credit_minutes_requested{{ slot.id }}">
                                {{ slot.credit_minutes_requested }}</span><br>
                            {% if not slot.publish_ok and slot.reserved_by == user %}
                            <span class="unpublished-msg">Task is unpublished but
                                appears on your dashboard!</span><br>
                            {% endif %}
                            {% if user.is_authenticated and slot.reserved_by == user %}
                            <span><button class="btn btn-edit btn-secondary btn-sm" 
                                data-slot_id="{{ slot.id }}">Edit</button> </span>
                            <span> <button class="btn btn-delete btn-danger btn-sm" 
                                data-slot_id="{{ slot.id }}">Delete</button></span>
                            {% endif %}
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</section>
<!-- The delete modal -->
<div id="deleteModal" class="modal" tabindex="-1" 
        aria-labelledby="deleteModalLabel" aria-hidden="True">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 id="deleteModalLabel" class="modal-title">
                    Are you sure?
                </h5>
                <button type="button" class="btn-close" 
                    data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>This action cannot be undone!
                    <br>You can always manage your tasks from your 
                        student dashboard.
                    </p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" 
                    data-bs-dismiss="modal">Cancel</button>
                <a id="deleteConfirm" href="#" class="btn btn-danger">Delete</a>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block extras %}
<script src="{% static 'js/slots.js' %}"></script>
{% endblock %}

</body>

volunteer/templates/volunteer/index.html
{% extends "base.html" %}
{% load static %}

{% block head_title %}Be a Dear{% endblock head_title %}

{% block content %}

<!-- Heading section-->
<section class="heading">
  <h1 class="d-none">Be a Dear</h1>
  <div class="container-fluid home-heading">
    <div class="row">
      <div class="col-sm-12 col-md-6 offset-md-3 col-lg-8 offset-lg-2 mb-5">
        <h1 class="display-4 text-center pt-5">
          Be a Dear is a Student-Led Project
        </h1>
        <h2 class="display-6 pt-3 text-center">
          designed to help us make the most of our mandatory volunteer hours
        </h2>
      </div>
    </div>
  </div>
  <div class="container-fluid g-0">
    <img src="{% static 'images/homepage-header-image.jpg' %}" 
        width="650" height="127" 
        class="card-img-top homepage-header-image" alt="Valentine hearts image">
  </div>
  <div class="container-fluid">
    <div class="row">
      <div class="col-12 py-4 mx-auto text-center">
        <h2 class="pt-3 text-center pt-4">Volunteer in non-traditional and 
          more fun, convenient and meaningful ways!</h2>
      </div>
    </div>
    <div class="row mb-5">
      <div class="col-sm-12 col-md-4 text-center py-3">
        <h2 class="display-6 mb-3">Discover Opportunities</h2>
        <p>On the <a href="{% url 'beneficiaries' %}" aria-label="link to volunteer page">
            Volunteer</a> page you'll find ideas and suggestions.</p>
        <p>Click on any of the choices to read more and start planning your activities.</p>
        <p>Be sure to take a look  at the ones labeled <strong>"Other"</strong> and <strong>"Individual"</strong></p>
        <p>They are what make this project truly special!</p>
      </div>
      <div class="col-sm-12 col-md-4 text-center py-3">
        <h2 class="display-6 mb-3">Your Personal Dashboard</h2>
        <p><a href="{% url 'account_login' %}" aria-label="link to login page">Sign in
            </a> to be able to save activities to your dashboard</p>
        <p>From there, you can plan and update your activities</p>
        <p>Request credit for hours completed</p>
        <p>Track your progress toward meeting the graduation requirement</p>
      </div>
      <div class="col-sm-12 col-md-4 text-center py-3">
        <h2 class="display-6 mb-3">Inspire one another!</h2>
        <p>See what others are signing up for</p>
        <p>Know of a good cause? Someone who could use a hand?</p>
        <p>Send us a <a href="{% url 'send_message' %}" aria-label="link to contact us form">
            message</a> and we'll post your suggestions here</p>
        <p>Read more about the project on the <a href="{% url 'about' %}"
            aria-label="link to the about page">About</a> page!</p>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

volunteer/templates/volunteer/student_page.html
{% inherit from "base.html" %}
{% load static %}
{% load cloudinary %}

{% if user.is_authorized %}
<div class="container-fluid">
    <div class="row">
        <div class="col-3">
            <img src="">
        </div>
            <h1>{{ user.first_name }} {{ user.last_name }}'s page</h1>
            <p>Manage your volunteer time and see your progress toward reaching the graduation requirement.</p>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class=col-12>
                <ul class="list-group">
                    <li class="list-group-item d-flex justify-content-between align-items-start">
                        <div class="ms-2 me-auto">
                            <div class="fw-bold">Planned</div>
                            Here, we'll loop through all of the slots reserved by the user that have not been
                                completed.
                        </div>
                        <span class="badge bg-primary rounded-pill">0 mins</span>
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-start">
                        <div class="ms-2 me-auto">
                            <div class="fw-bold">Completed</div>
                            Here, we'll loop through all of the slots reserved by the user that have completed and
                            need to request teacher approval for a specific number of minutes greater than zero.
                        </div>
                        <span class="badge bg-primary rounded-pill">14</span>
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-start">
                        <div class="ms-2 me-auto">
                            <div class="fw-bold">Approved</div>
                            Here, we'll loop through all of the slots approved by the teacher, displaying the minutes approved.
                        </div>
                        <span class="badge bg-primary rounded-pill">14</span>
                    </li>
                </ul>
            </div>
        <div class="row">
            <div class="col-6">
                    <p>Minutes approved to date:</p>
            </div>
            <div class="col-6">Write some code to get the total!</div>
        </div>
    </div>
</div>

volunteer/templates/volunteer/update_task.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block head_title %}Update Task{% endblock head_title %}

{% block content %}

<section id="edit-task">
    <h1 class="d-none">Updating a Task</h1>
    {% if user.is_authenticated and slot.reserved_by == user %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-8 offset offset-md-2 col-lg-6 offset-lg-3">
                <h1>Update a task:</h1>
                <form id="slotForm" class="mb-5" method="post" action="">
                    {{ form | crispy }}
                    {% csrf_token %}
                    <button id="updateButton" type="submit" class="btn btn-secondary btn-lg">
                        Update</button>
                </form>
            </div>
        </div>
    </div>
    {% else %}
    <div>
        <h1>You must be logged in to manage your tasks.</h1>
    </div>
    {% endif %}
    </div>
</section>

{% endblock %}

volunteer/templates/volunteer/volunteer_opportunities.html
{% extends "base.html" %}
{% load static %}

{% block head_title %}Volunteer Opportunities{% endblock head_title %}

{% block content %}
<section class="beneficiaries-list">
  <h1 class="d-none">Volunteer Opportunities</h1>
  <div class="container-fluid text-center">
    <div class="row">
      <div class="col-12 text-center heading-beneficiaries">
        <h2 class="display-4 my-3">Here are the opportunities that we know of so far.</h2>
        <p class="display-6 mb-5">We trust you'll be sending in your ideas for more as the project progresses!</p>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-12 col-md-6 offset-md-3 mx-auto text-center how-it-works">
        <h3 class="display-6 my-3">
          How it Works:
        </h3>
        <h4 class="mt-2 mb-2">
          Click on any of the items below to read more. From there,
          if you're interested, you'll be able to save tasks related
          to that beneficiary to your dashboard.
        </h4>
        <h3 class="my-3">
          Note especially the categories of "Other" and "Individual" below
        </h3>
        <h4 class="mb-5">
          These will allow you plan volunteer activities (and request credit!)
          for people or organizations not already listed here.
        </h4>
      </div>
    </div>
  </div>
  <div class="container-fluid beneficiary-container d-flex justify-content-evenly pb-5 mb-5">
    <div class="row mx-auto">
      <!-- Cards for each beneficiary in list -->
      {% for beneficiary in beneficiary_list %}
      <div class="card b-card bg-transparent mx-auto px-5 my-2 col-sm-12, col-md-6 col-lg-3 g-0">
        <div class="card-body">
          <h5 class="card-title card-small-h3">
            <a href="{% url 'beneficiary_detail' beneficiary.slug %}" 
                aria-label="link to the beneficiary">{{ beneficiary.beneficiary_name }}
            </a>
          </h5>
          <h6 class="card-subtitle mb-2 text-muted card-small-h4">
            <small>{{ beneficiary.location }}</small>
          </h6>
          <article class="card-text" title="beneficiary-description">
            {{ beneficiary.short_description | safe }}
            <p class="card-text">{{ beneficiary.contact_details }}</p>
          </article>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>
{% endblock%}